name: Build RAG index
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  rag-index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install sentence-transformers faiss-cpu scikit-learn nltk markdown-it-py

      - name: Build index
        run: |
          python .rag/build_index.py

      - name: Commit artifacts
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .rag/chunks.jsonl .rag/keywords.jsonl .rag/neighbors.jsonl .rag/toc.json || true
          git diff --cached --quiet || git commit -m "chore(rag): refresh index"
          git push
